version: '2'

services:
    nodejs:
      build: .
      image: aleprieto/node-ionic
      ports:
        - "8100:8100"
        - "35729:35729"
        - "53703:53703"
      restart: always
      command: bash -c "cd /var/www/html/ionic-osm && ionic serve --all"
      # command: bash -c "tail -f /dev/null"
      volumes:
        - ./src:/var/www/html